### ISSUE TITLE
Is it possible to use MSI to query Azure AD

### ISSUE THREAD

**Issue by fgheysels** [pim-simons/azuread.application.clientsecret.expiration#1]
I think this is really nice work, and it's a usefull function.   
There's one thing however that can possibly be improved:  the Function is now using a separate app registration & client secret to query Azure AD.   Wouldn't it be possible to use Azure Managed Identity for this ?

**Comment by pim-simons** [comment]
Good suggestion, seems like a good improvement. 
Definately something to take up when moving this to Arcus Backgroundjobs!

**Comment by pim-simons** [comment]
See https://github.com/pim-simons/azuread.application.clientsecret.expiration/commit/03343fc4f59bc2fd254e9446b120567789d2003b
Changed to Managed Identity, did some tests and works fine 👍🏻
